#Deploying a Kubernetes architecture on Amazon EKS following the follow features 
#Deployments,DaemonSets,Rolling update and Rollbacks,Scaling in Kubernetes,Deploying Services,Persistent Volumes and Persistent Volume Claims
#ConfigMaps and Secrets,Helm Charts


apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:v1
          ports:
            - containerPort: 80



#This deployment will create three replicas of a container running an image called my-image:latest.
# It also defines a service that can be used to access the deployed application.